In [1]:
import numpy as np
a=np.array([6,7,8])
print(a[0:2])

[6 7]


In [5]:
a=np.array([[6,7,8],[9,10,11],[12,13,14]])
print(a)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [6]:
a[0:2,2]

array([ 8, 11])

In [7]:
a[-1]

array([12, 13, 14])

In [8]:
for row in a:
    print(row)

[6 7 8]
[ 9 10 11]
[12 13 14]


In [9]:
for cell in a.flat:
    print(cell)

6
7
8
9
10
11
12
13
14


In [10]:
a=np.arange(6).reshape(3,2)
b=np.arange(6,12).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [11]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [12]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [13]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [14]:
a=np.arange(30).reshape(2,15)
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [15]:
r=np.hsplit(a,3)
r[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [16]:
r[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [17]:
b=a>7
b

array([[False, False, False, False, False, False, False, False,  True,
         True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True]])

In [18]:
a[b]

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 29])

In [21]:
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [26]:
for x in np.nditer(a,order='F',flags=['external_loop']):
    print(x)

[0 3 6 9]
[ 1  4  7 10]
[ 2  5  8 11]


In [41]:
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
for x in np.nditer(a,op_flags=['readwrite']):
    x[...]= x*x

In [43]:
a

array([[  0,   1,   4],
       [  9,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121]])

In [45]:
b=np.arange(3,15,4).reshape(3,1)
b

array([[ 3],
       [ 7],
       [11]])

In [48]:
a=a.reshape(3,4)

In [49]:
for x,y in np.nditer([a,b]):
    print(x,y)

0 3
1 3
4 3
9 3
16 7
25 7
36 7
49 7
64 11
81 11
100 11
121 11
